name: Build PDF

on:
  workflow_call:
    inputs:
      relative_path:
        description: "Relative Project Path"
        required: true
        type: string
      pdf_name:
        description: "PDF name"
        required: true
        type: string
      send_it:
        description: "Sends the email if true"
        required: false
        type: boolean
        default: false
      email_to:
        description: "Recipient email address"
        required: false
        type: string
      email_subject:
        description: "Custom subject line for email"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build PDF with LuaLaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ inputs.relative_path }}/main.tex
          latexmk_use_lualatex: true
          cache: true
      - name: Create output folder
        run: |
          mkdir -p build/${{ inputs.relative_path }}
          mv ${{ inputs.relative_path }}/${{ inputs.pdf_name }}.pdf build/${{ inputs.relative_path }}/


      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ inputs.relative_path }}
          path: build/${{ inputs.pdf_name }}.pdf

      - name: Ensure PDF was generated
        run: test -f build/${{ inputs.pdf_name }}.pdf

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          clean: true
          single-commit: true
          git-config-name: github-actions
          git-config-email: github-actions@github.com

      - name: Send email with PDF
        if: ${{ inputs.send_it && inputs.email_to != '' && inputs.email_to != null }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${{ inputs.email_subject || format('New PDF - {0} from {1}', inputs.relative_path, github.repository) }}
          to: ${{ inputs.email_to }}
          from: "GitHub Actions <${{ secrets.MAIL_USERNAME }}>"
          body: "The latest PDF has been built and is attached."
          attachments: build/${{ inputs.pdf_name }}.pdf
