name: Build PDF

on:
  workflow_call:
    inputs:
      relative_path:
        description: "Relative path to the LaTeX project folder"
        required: true
        type: string
      pdf_name:
        description: "PDF name (without extension, defaults to 'main')"
        required: false
        type: string
        default: "main"
      send_it:
        description: "Whether to send the PDF via email"
        required: false
        type: boolean
        default: false
      email_to:
        description: "Recipient email address"
        required: false
        type: string
      email_subject:
        description: "Custom email subject"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project repo
        uses: actions/checkout@v4

      - name: Checkout HomeworkTemplate
        uses: actions/checkout@v4
        with:
          repository: MarcosLopezM/HomeworkTemplate
          path: hw-template

      - name: Build PDF with LuaLaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: ${{ inputs.relative_path }}/${{ inputs.pdf_name }}.tex
          work_in_root_file_dir: true
          extra_fonts: |
            ../hw-template/fonts/linux-libertine/*.otf
            ../hw-template/fonts/linux-biolinum/*.otf
          pre_compile: "mktexlsr && luaotfload-tool -fu && fc-cache -fv"
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
        env:
          TEXINPUTS: ".:$GITHUB_WORKSPACE/hw-template//:"
        

      - name: Create output folder
        run: |
          mkdir -p build/${{ inputs.relative_path }}
          mv ${{ inputs.relative_path }}/${{ inputs.pdf_name }}.pdf build/${{ inputs.relative_path }}/

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ inputs.relative_path }}
          path: build/${{ inputs.relative_path }}/${{ inputs.pdf_name }}.pdf

      - name: Ensure PDF was generated
        run: test -f build/${{ inputs.relative_path }}/${{ inputs.pdf_name }}.pdf

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          clean: true
          single-commit: true
          git-config-name: github-actions
          git-config-email: github-actions@github.com

      - name: Send email with PDF
        if: ${{ inputs.send_it && inputs.email_to != '' && inputs.email_to != null }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${{ inputs.email_subject != '' && inputs.email_subject || format('New PDF from {0}/{1}', github.repository, inputs.relative_path) }}
          to: ${{ inputs.email_to }}
          from: "GitHub Actions <${{ secrets.MAIL_USERNAME }}>"
          body: "The latest PDF has been built and is attached."
          attachments: build/${{ inputs.relative_path }}/${{ inputs.pdf_name }}.pdf
